apiVersion: v1
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    error_log /mylog/error.log warn;
    pid /var/run/nginx.pid;
    events {
                worker_connections 1024;
      }
    http {
       log_format  main
          'remote_addr:$remote_addr\t'
          'time_local:$time_local\t'
          'status:$status\t';
       include  /etc/nginx/mime.types;
       default_type application/octet-stream;
       sendfile on;
       keepalive_timeout  65;
       include /etc/nginx/conf.d/*.conf;
       }
     stream {
       log_format  main
         'server_port:$server_port\t'
         'remote_addr:$remote_addr\t'
         'time_local:$time_local\t'
         'status:$status\t'
         'ssl_protocol:$ssl_protocol\t'
         'ssl_cipher:$ssl_cipher\t'
         'remote_addr:$remote_addr\t'
         'ssl_client_supported_ciphers:$ssl_ciphers\t';
       ssl_certificate /tmp/server.crt;
       ssl_certificate_key /tmp/server.key;
       ssl_trusted_certificate /tmp/ca.crt;
       #ssl_protocols TLSv1.3;
       #ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384;
       ssl_prefer_server_ciphers on;
       ssl_handshake_timeout 2s;
       error_log /mylog/app.error_log debug;
       access_log /mylog/app.access_log main;
       include /config/*.conf;
      }
kind: ConfigMap
metadata:
  name: nginx-config
